spring:
  jpa:
    hibernate:
      # ?????? ?? ??? ??? ??? ?? ?? ???? ???. create-drop ? ???? ???? ? ???.
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password: 12

logging:
  level:
    # ??? ???? ????.
    org.hibernate.SQL: debug
    org.hibernate.type: debug
